version: "3.8"
services:
    db:
        container_name: database_hr_roster
        hostname: mysql
        image: mysql:5.7
        ports:
          - "3311:3306"
        restart: always
        environment:
          MYSQL_DATABASE: hr_platform_db
          MYSQL_USER: amrilsyaifa
          MYSQL_PASSWORD: Am12il1991!
          MYSQL_ROOT_PASSWORD: Am12il1991!
        volumes:
          - persistent:/var/lib/mysql
          - ./files:/files
        networks:
          - default
volumes:
    persistent: